// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriviaGameAPI.DAL.Repositories;

#nullable disable

namespace TriviaGameAPI.DAL.Migrations
{
    [DbContext(typeof(TriviaGameDBContext))]
    partial class TriviaGameDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_NC_Answer_Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_CL_Category_Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Actor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animal"
                        },
                        new
                        {
                            Id = 4,
                            Name = "City"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Drink"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Vehicle"
                        });
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.GameplayRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_CL_GameRoom_Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("GameplayRooms");
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterColor")
                        .HasMaxLength(9)
                        .HasColumnType("varchar");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("GameplayRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsGameOrganizer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastGameDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PL_NC_Player_Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("GameplayRoomId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 4, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3249),
                            Name = "Player0",
                            Score = 347
                        },
                        new
                        {
                            Id = 2,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 16, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3258),
                            Name = "Player1",
                            Score = 659
                        },
                        new
                        {
                            Id = 3,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 18, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3259),
                            Name = "Player2",
                            Score = 599
                        },
                        new
                        {
                            Id = 4,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 14, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3261),
                            Name = "Player3",
                            Score = 152
                        },
                        new
                        {
                            Id = 5,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 12, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3263),
                            Name = "Player4",
                            Score = 533
                        },
                        new
                        {
                            Id = 6,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 17, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3265),
                            Name = "Player5",
                            Score = 230
                        },
                        new
                        {
                            Id = 7,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 10, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3267),
                            Name = "Player6",
                            Score = 281
                        },
                        new
                        {
                            Id = 8,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 7, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3269),
                            Name = "Player7",
                            Score = 292
                        },
                        new
                        {
                            Id = 9,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 11, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3271),
                            Name = "Player8",
                            Score = 347
                        },
                        new
                        {
                            Id = 10,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 7, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3273),
                            Name = "Player9",
                            Score = 541
                        },
                        new
                        {
                            Id = 11,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 29, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3275),
                            Name = "Player10",
                            Score = 613
                        },
                        new
                        {
                            Id = 12,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 9, 29, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3277),
                            Name = "Player11",
                            Score = 577
                        },
                        new
                        {
                            Id = 13,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 7, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3278),
                            Name = "Player12",
                            Score = 277
                        },
                        new
                        {
                            Id = 14,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 9, 30, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3280),
                            Name = "Player13",
                            Score = 310
                        },
                        new
                        {
                            Id = 15,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 13, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3282),
                            Name = "Player14",
                            Score = 612
                        },
                        new
                        {
                            Id = 16,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3284),
                            Name = "Player15",
                            Score = 601
                        },
                        new
                        {
                            Id = 17,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 17, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3286),
                            Name = "Player16",
                            Score = 153
                        },
                        new
                        {
                            Id = 18,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 19, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3287),
                            Name = "Player17",
                            Score = 265
                        },
                        new
                        {
                            Id = 19,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 3, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3289),
                            Name = "Player18",
                            Score = 543
                        },
                        new
                        {
                            Id = 20,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 25, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3291),
                            Name = "Player19",
                            Score = 668
                        },
                        new
                        {
                            Id = 21,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 15, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3292),
                            Name = "Player20",
                            Score = 616
                        },
                        new
                        {
                            Id = 22,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 10, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3294),
                            Name = "Player21",
                            Score = 96
                        },
                        new
                        {
                            Id = 23,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 5, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3296),
                            Name = "Player22",
                            Score = 5
                        },
                        new
                        {
                            Id = 24,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 1, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3297),
                            Name = "Player23",
                            Score = 97
                        },
                        new
                        {
                            Id = 25,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 20, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3299),
                            Name = "Player24",
                            Score = 538
                        },
                        new
                        {
                            Id = 26,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 13, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3300),
                            Name = "Player25",
                            Score = 236
                        },
                        new
                        {
                            Id = 27,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 14, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3302),
                            Name = "Player26",
                            Score = 246
                        },
                        new
                        {
                            Id = 28,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 29, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3304),
                            Name = "Player27",
                            Score = 577
                        },
                        new
                        {
                            Id = 29,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 7, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3306),
                            Name = "Player28",
                            Score = 86
                        },
                        new
                        {
                            Id = 30,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 6, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3308),
                            Name = "Player29",
                            Score = 497
                        },
                        new
                        {
                            Id = 31,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 2, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3309),
                            Name = "Player30",
                            Score = 266
                        },
                        new
                        {
                            Id = 32,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 24, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3311),
                            Name = "Player31",
                            Score = 154
                        },
                        new
                        {
                            Id = 33,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 16, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3313),
                            Name = "Player32",
                            Score = 427
                        },
                        new
                        {
                            Id = 34,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 16, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3315),
                            Name = "Player33",
                            Score = 50
                        },
                        new
                        {
                            Id = 35,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 30, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3346),
                            Name = "Player34",
                            Score = 517
                        },
                        new
                        {
                            Id = 36,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 14, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3348),
                            Name = "Player35",
                            Score = 567
                        },
                        new
                        {
                            Id = 37,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 12, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3350),
                            Name = "Player36",
                            Score = 507
                        },
                        new
                        {
                            Id = 38,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 9, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3351),
                            Name = "Player37",
                            Score = 277
                        },
                        new
                        {
                            Id = 39,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 7, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3353),
                            Name = "Player38",
                            Score = 648
                        },
                        new
                        {
                            Id = 40,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 19, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3355),
                            Name = "Player39",
                            Score = 609
                        },
                        new
                        {
                            Id = 41,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 25, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3357),
                            Name = "Player40",
                            Score = 551
                        },
                        new
                        {
                            Id = 42,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 8, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3358),
                            Name = "Player41",
                            Score = 491
                        },
                        new
                        {
                            Id = 43,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 10, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3360),
                            Name = "Player42",
                            Score = 646
                        },
                        new
                        {
                            Id = 44,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 8, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3362),
                            Name = "Player43",
                            Score = 136
                        },
                        new
                        {
                            Id = 45,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 28, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3364),
                            Name = "Player44",
                            Score = 698
                        },
                        new
                        {
                            Id = 46,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 3, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3365),
                            Name = "Player45",
                            Score = 488
                        },
                        new
                        {
                            Id = 47,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 11, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3367),
                            Name = "Player46",
                            Score = 699
                        },
                        new
                        {
                            Id = 48,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 21, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3369),
                            Name = "Player47",
                            Score = 544
                        },
                        new
                        {
                            Id = 49,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 25, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3371),
                            Name = "Player48",
                            Score = 497
                        },
                        new
                        {
                            Id = 50,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 11, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3373),
                            Name = "Player49",
                            Score = 454
                        },
                        new
                        {
                            Id = 51,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 21, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3374),
                            Name = "Player50",
                            Score = 564
                        },
                        new
                        {
                            Id = 52,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 25, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3376),
                            Name = "Player51",
                            Score = 426
                        },
                        new
                        {
                            Id = 53,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 9, 28, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3377),
                            Name = "Player52",
                            Score = 679
                        },
                        new
                        {
                            Id = 54,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 21, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3379),
                            Name = "Player53",
                            Score = 338
                        },
                        new
                        {
                            Id = 55,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 7, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3381),
                            Name = "Player54",
                            Score = 503
                        },
                        new
                        {
                            Id = 56,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 15, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3383),
                            Name = "Player55",
                            Score = 442
                        },
                        new
                        {
                            Id = 57,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 21, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3384),
                            Name = "Player56",
                            Score = 425
                        },
                        new
                        {
                            Id = 58,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 14, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3386),
                            Name = "Player57",
                            Score = 139
                        },
                        new
                        {
                            Id = 59,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3388),
                            Name = "Player58",
                            Score = 87
                        },
                        new
                        {
                            Id = 60,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 13, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3389),
                            Name = "Player59",
                            Score = 547
                        },
                        new
                        {
                            Id = 61,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 15, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3391),
                            Name = "Player60",
                            Score = 159
                        },
                        new
                        {
                            Id = 62,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 19, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3393),
                            Name = "Player61",
                            Score = 89
                        },
                        new
                        {
                            Id = 63,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 9, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3394),
                            Name = "Player62",
                            Score = 392
                        },
                        new
                        {
                            Id = 64,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 7, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3396),
                            Name = "Player63",
                            Score = 393
                        },
                        new
                        {
                            Id = 65,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 27, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3398),
                            Name = "Player64",
                            Score = 2
                        },
                        new
                        {
                            Id = 66,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 5, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3399),
                            Name = "Player65",
                            Score = 193
                        },
                        new
                        {
                            Id = 67,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 20, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3401),
                            Name = "Player66",
                            Score = 313
                        },
                        new
                        {
                            Id = 68,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 12, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3403),
                            Name = "Player67",
                            Score = 10
                        },
                        new
                        {
                            Id = 69,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 23, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3404),
                            Name = "Player68",
                            Score = 589
                        },
                        new
                        {
                            Id = 70,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 13, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3406),
                            Name = "Player69",
                            Score = 607
                        },
                        new
                        {
                            Id = 71,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 22, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3408),
                            Name = "Player70",
                            Score = 145
                        },
                        new
                        {
                            Id = 72,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 5, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3409),
                            Name = "Player71",
                            Score = 548
                        },
                        new
                        {
                            Id = 73,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 23, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3411),
                            Name = "Player72",
                            Score = 362
                        },
                        new
                        {
                            Id = 74,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 3, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3412),
                            Name = "Player73",
                            Score = 500
                        },
                        new
                        {
                            Id = 75,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 8, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3414),
                            Name = "Player74",
                            Score = 363
                        },
                        new
                        {
                            Id = 76,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3416),
                            Name = "Player75",
                            Score = 562
                        },
                        new
                        {
                            Id = 77,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 9, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3418),
                            Name = "Player76",
                            Score = 662
                        },
                        new
                        {
                            Id = 78,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3420),
                            Name = "Player77",
                            Score = 542
                        },
                        new
                        {
                            Id = 79,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3421),
                            Name = "Player78",
                            Score = 611
                        },
                        new
                        {
                            Id = 80,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 9, 29, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3423),
                            Name = "Player79",
                            Score = 691
                        },
                        new
                        {
                            Id = 81,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 23, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3425),
                            Name = "Player80",
                            Score = 429
                        },
                        new
                        {
                            Id = 82,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 9, 30, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3426),
                            Name = "Player81",
                            Score = 40
                        },
                        new
                        {
                            Id = 83,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 13, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3428),
                            Name = "Player82",
                            Score = 534
                        },
                        new
                        {
                            Id = 84,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 17, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3430),
                            Name = "Player83",
                            Score = 394
                        },
                        new
                        {
                            Id = 85,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 18, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3431),
                            Name = "Player84",
                            Score = 244
                        },
                        new
                        {
                            Id = 86,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 14, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3433),
                            Name = "Player85",
                            Score = 309
                        },
                        new
                        {
                            Id = 87,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 31, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3435),
                            Name = "Player86",
                            Score = 338
                        },
                        new
                        {
                            Id = 88,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 22, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3436),
                            Name = "Player87",
                            Score = 674
                        },
                        new
                        {
                            Id = 89,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 25, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3438),
                            Name = "Player88",
                            Score = 672
                        },
                        new
                        {
                            Id = 90,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 12, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3440),
                            Name = "Player89",
                            Score = 239
                        },
                        new
                        {
                            Id = 91,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 15, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3441),
                            Name = "Player90",
                            Score = 210
                        },
                        new
                        {
                            Id = 92,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3443),
                            Name = "Player91",
                            Score = 699
                        },
                        new
                        {
                            Id = 93,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 8, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3445),
                            Name = "Player92",
                            Score = 520
                        },
                        new
                        {
                            Id = 94,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 4, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3446),
                            Name = "Player93",
                            Score = 505
                        },
                        new
                        {
                            Id = 95,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 9, 29, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3448),
                            Name = "Player94",
                            Score = 171
                        },
                        new
                        {
                            Id = 96,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3450),
                            Name = "Player95",
                            Score = 28
                        },
                        new
                        {
                            Id = 97,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 10, 1, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3452),
                            Name = "Player96",
                            Score = 529
                        },
                        new
                        {
                            Id = 98,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 10, 29, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3453),
                            Name = "Player97",
                            Score = 135
                        },
                        new
                        {
                            Id = 99,
                            IsGameOrganizer = true,
                            LastGameDate = new DateTime(2022, 11, 26, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3455),
                            Name = "Player98",
                            Score = 460
                        },
                        new
                        {
                            Id = 100,
                            IsGameOrganizer = false,
                            LastGameDate = new DateTime(2022, 11, 18, 9, 28, 52, 864, DateTimeKind.Utc).AddTicks(3456),
                            Name = "Player99",
                            Score = 284
                        });
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id")
                        .HasName("PK_CL_Question_Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("CategoryId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Answer", b =>
                {
                    b.HasOne("TriviaGameAPI.DAL.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Player", b =>
                {
                    b.HasOne("TriviaGameAPI.DAL.Models.GameplayRoom", null)
                        .WithMany("Players")
                        .HasForeignKey("GameplayRoomId");
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Question", b =>
                {
                    b.HasOne("TriviaGameAPI.DAL.Models.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TriviaGameAPI.DAL.Models.GameplayRoom", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
